nelmio_api_doc:
    documentation:
        info:
            title: BileMo API
            description: Mobile phones API documentation
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^(?!(/$|/_)) # Accepts routes under /api except /api/doc
